name: nfx-stringutils - Windows MinGW

on:
  push:
    branches: [main]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "samples/**"
      - "benchmark/**"
      - "CMakeLists.txt"
      - ".github/workflows/build-windows-mingw.yml"
  pull_request:
    branches: [main]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "samples/**"
      - "benchmark/**"
      - "CMakeLists.txt"
      - ".github/workflows/build-windows-mingw.yml"

env:
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  build-windows-mingw:
    runs-on: windows-2022
    name: Windows MinGW

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Cache CMake build and ccache
        uses: actions/cache@v4
        with:
          path: |
            build
            ${{ runner.temp }}/ccache
          key: ${{ runner.os }}-mingw-cmake-${{ hashFiles('**/CMakeLists.txt', 'include/**', 'src/**') }}
          restore-keys: |
            ${{ runner.os }}-mingw-cmake-

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-ccache

      - name: Setup ccache
        shell: msys2 {0}
        run: |
          export CCACHE_DIR="${{ runner.temp }}/ccache"
          export CCACHE_COMPILERCHECK=content
          export CCACHE_COMPRESS=true
          export CCACHE_MAXSIZE=200M
          mkdir -p "$CCACHE_DIR"
          ccache --zero-stats
          ccache --show-config

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          export CC="ccache gcc"
          export CXX="ccache g++"
          export CCACHE_DIR="${{ runner.temp }}/ccache"
          cmake -B build \
                -G "Ninja" \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DNFX_STRINGUTILS_BUILD_TESTS=ON \
                -DNFX_STRINGUTILS_BUILD_SAMPLES=OFF \
                -DNFX_STRINGUTILS_BUILD_BENCHMARKS=OFF \
                -DNFX_STRINGUTILS_BUILD_DOCUMENTATION=OFF

      - name: Build
        shell: msys2 {0}
        run: |
          export CCACHE_DIR="${{ runner.temp }}/ccache"
          cmake --build build --parallel

      - name: Test
        shell: msys2 {0}
        working-directory: build
        run: ctest --output-on-failure --parallel

      - name: Show ccache statistics
        shell: msys2 {0}
        run: |
          export CCACHE_DIR="${{ runner.temp }}/ccache"
          ccache --show-stats
